services:
  db:
    image: mariadb:10.11
    container_name: northsmith-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql
      - ./database/wordpress_db.sql:/docker-entrypoint-initdb.d/01-dump.sql:ro
    ports:
      - "3307:3306"

  wordpress:
    image: wordpress:6.7-php8.2-apache
    container_name: northsmith-wp
    restart: unless-stopped
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: northsmith-pma
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"

volumes:
  db_data: